AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lab-1

  Sample SAM Template for lab-1

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ChallengeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: challenge-function/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        CreateChallenge:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /challenge
            Method: post
        GetChallenge:
          Type: Api
          Properties:
            Path: /challenge/{id}
            Method: get
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
              Resource:
                "arn:aws:dynamodb:*:*:table/challenge-table"
  ChallengeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: challenge-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/challenge/"
  ChallengeFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ChallengeFunction.Arn
  ChallengeFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ChallengeFunctionRole.Arn
